package enums;

import java.util.HashMap;
import java.util.Map;

public class Mnemonics {
    private final Map<String, Integer> mnemonicsByString;
    private final Map<Integer, String> mnemonicsByOpcode;

    public Mnemonics() {
        this.mnemonicsByString = new HashMap<>();
        this.mnemonicsByOpcode = new HashMap<>();
        this.fillMap();
    }

    private void fillMap() {
        this.mnemonicsByString.put("nop", 0);
        this.mnemonicsByString.put("aconst_null", 1);
        this.mnemonicsByString.put("iconst_m1", 2);
        this.mnemonicsByString.put("iconst_0", 3);
        this.mnemonicsByString.put("iconst_1", 4);
        this.mnemonicsByString.put("iconst_2", 5);
        this.mnemonicsByString.put("iconst_3", 6);
        this.mnemonicsByString.put("iconst_4", 7);
        this.mnemonicsByString.put("iconst_5", 8);
        this.mnemonicsByString.put("lconst_0", 9);
        this.mnemonicsByString.put("lconst_1", 10);
        this.mnemonicsByString.put("fconst_0", 11);
        this.mnemonicsByString.put("fconst_1", 12);
        this.mnemonicsByString.put("fconst_2", 13);
        this.mnemonicsByString.put("dconst_0", 14);
        this.mnemonicsByString.put("dconst_1", 15);
        this.mnemonicsByString.put("bipush", 16);
        this.mnemonicsByString.put("sipush", 17);
        this.mnemonicsByString.put("ldc", 18);
        this.mnemonicsByString.put("ldc_w", 19);
        this.mnemonicsByString.put("ldc2_w", 20);
        this.mnemonicsByString.put("iload", 21);
        this.mnemonicsByString.put("lload", 22);
        this.mnemonicsByString.put("fload", 23);
        this.mnemonicsByString.put("dload", 24);
        this.mnemonicsByString.put("aload", 25);
        this.mnemonicsByString.put("iload_0", 26);
        this.mnemonicsByString.put("iload_1", 27);
        this.mnemonicsByString.put("iload_2", 28);
        this.mnemonicsByString.put("iload_3", 29);
        this.mnemonicsByString.put("lload_0", 30);
        this.mnemonicsByString.put("lload_1", 31);
        this.mnemonicsByString.put("lload_2", 32);
        this.mnemonicsByString.put("lload_3", 33);
        this.mnemonicsByString.put("fload_0", 34);
        this.mnemonicsByString.put("fload_1", 35);
        this.mnemonicsByString.put("fload_2", 36);
        this.mnemonicsByString.put("fload_3", 37);
        this.mnemonicsByString.put("dload_0", 38);
        this.mnemonicsByString.put("dload_1", 39);
        this.mnemonicsByString.put("dload_2", 40);
        this.mnemonicsByString.put("dload_3", 41);
        this.mnemonicsByString.put("aload_0", 42);
        this.mnemonicsByString.put("aload_1", 43);
        this.mnemonicsByString.put("aload_2", 44);
        this.mnemonicsByString.put("aload_3", 45);
        this.mnemonicsByString.put("iaload", 46);
        this.mnemonicsByString.put("laload", 47);
        this.mnemonicsByString.put("faload", 48);
        this.mnemonicsByString.put("daload", 49);
        this.mnemonicsByString.put("aaload", 50);
        this.mnemonicsByString.put("baload", 51);
        this.mnemonicsByString.put("caload", 52);
        this.mnemonicsByString.put("saload", 53);
        this.mnemonicsByString.put("istore", 54);
        this.mnemonicsByString.put("lstore", 55);
        this.mnemonicsByString.put("fstore", 56);
        this.mnemonicsByString.put("dstore", 57);
        this.mnemonicsByString.put("astore", 58);
        this.mnemonicsByString.put("istore_0", 59);
        this.mnemonicsByString.put("istore_1", 60);
        this.mnemonicsByString.put("istore_2", 61);
        this.mnemonicsByString.put("istore_3", 62);
        this.mnemonicsByString.put("lstore_0", 63);
        this.mnemonicsByString.put("lstore_1", 64);
        this.mnemonicsByString.put("lstore_2", 65);
        this.mnemonicsByString.put("lstore_3", 66);
        this.mnemonicsByString.put("fstore_0", 67);
        this.mnemonicsByString.put("fstore_1", 68);
        this.mnemonicsByString.put("fstore_2", 69);
        this.mnemonicsByString.put("fstore_3", 70);
        this.mnemonicsByString.put("dstore_0", 71);
        this.mnemonicsByString.put("dstore_1", 72);
        this.mnemonicsByString.put("dstore_2", 73);
        this.mnemonicsByString.put("dstore_3", 74);
        this.mnemonicsByString.put("astore_0", 75);
        this.mnemonicsByString.put("astore_1", 76);
        this.mnemonicsByString.put("astore_2", 77);
        this.mnemonicsByString.put("astore_3", 78);
        this.mnemonicsByString.put("iastore", 79);
        this.mnemonicsByString.put("lastore", 80);
        this.mnemonicsByString.put("fastore", 81);
        this.mnemonicsByString.put("dastore", 82);
        this.mnemonicsByString.put("aastore", 83);
        this.mnemonicsByString.put("bastore", 84);
        this.mnemonicsByString.put("castore", 85);
        this.mnemonicsByString.put("sastore", 86);
        this.mnemonicsByString.put("pop", 87);
        this.mnemonicsByString.put("pop2", 88);
        this.mnemonicsByString.put("dup", 89);
        this.mnemonicsByString.put("dup_x1", 90);
        this.mnemonicsByString.put("dup_x2", 91);
        this.mnemonicsByString.put("dup2", 92);
        this.mnemonicsByString.put("dup2_x1", 93);
        this.mnemonicsByString.put("dup2_x2", 94);
        this.mnemonicsByString.put("swap", 95);
        this.mnemonicsByString.put("iadd", 96);
        this.mnemonicsByString.put("ladd", 97);
        this.mnemonicsByString.put("fadd", 98);
        this.mnemonicsByString.put("dadd", 99);
        this.mnemonicsByString.put("isub", 100);
        this.mnemonicsByString.put("lsub", 101);
        this.mnemonicsByString.put("fsub", 102);
        this.mnemonicsByString.put("dsub", 103);
        this.mnemonicsByString.put("imul", 104);
        this.mnemonicsByString.put("lmul", 105);
        this.mnemonicsByString.put("fmul", 106);
        this.mnemonicsByString.put("dmul", 107);
        this.mnemonicsByString.put("idiv", 108);
        this.mnemonicsByString.put("ldiv", 109);
        this.mnemonicsByString.put("fdiv", 110);
        this.mnemonicsByString.put("ddiv", 111);
        this.mnemonicsByString.put("irem", 112);
        this.mnemonicsByString.put("lrem", 113);
        this.mnemonicsByString.put("frem", 114);
        this.mnemonicsByString.put("drem", 115);
        this.mnemonicsByString.put("ineg", 116);
        this.mnemonicsByString.put("lneg", 117);
        this.mnemonicsByString.put("fneg", 118);
        this.mnemonicsByString.put("dneg", 119);
        this.mnemonicsByString.put("ishl", 120);
        this.mnemonicsByString.put("lshl", 121);
        this.mnemonicsByString.put("ishr", 122);
        this.mnemonicsByString.put("lshr", 123);
        this.mnemonicsByString.put("iushr", 124);
        this.mnemonicsByString.put("lushr", 125);
        this.mnemonicsByString.put("iand", 126);
        this.mnemonicsByString.put("land", 127);
        this.mnemonicsByString.put("ior", 128);
        this.mnemonicsByString.put("lor", 129);
        this.mnemonicsByString.put("ixor", 130);
        this.mnemonicsByString.put("lxor", 131);
        this.mnemonicsByString.put("iinc", 132);
        this.mnemonicsByString.put("i2l", 133);
        this.mnemonicsByString.put("i2f", 134);
        this.mnemonicsByString.put("i2d", 135);
        this.mnemonicsByString.put("l2i", 136);
        this.mnemonicsByString.put("l2f", 137);
        this.mnemonicsByString.put("l2d", 138);
        this.mnemonicsByString.put("f2i", 139);
        this.mnemonicsByString.put("f2l", 140);
        this.mnemonicsByString.put("f2d", 141);
        this.mnemonicsByString.put("d2i", 142);
        this.mnemonicsByString.put("d2l", 143);
        this.mnemonicsByString.put("d2f", 144);
        this.mnemonicsByString.put("i2b", 145);
        this.mnemonicsByString.put("i2c", 146);
        this.mnemonicsByString.put("i2s", 147);
        this.mnemonicsByString.put("lcmp", 148);
        this.mnemonicsByString.put("fcmpl", 149);
        this.mnemonicsByString.put("fcmpg", 150);
        this.mnemonicsByString.put("dcmpl", 151);
        this.mnemonicsByString.put("dcmpg", 152);
        this.mnemonicsByString.put("ifeq", 153);
        this.mnemonicsByString.put("ifne", 154);
        this.mnemonicsByString.put("iflt", 155);
        this.mnemonicsByString.put("ifge", 156);
        this.mnemonicsByString.put("ifgt", 157);
        this.mnemonicsByString.put("ifle", 158);
        this.mnemonicsByString.put("if_icmpeq", 159);
        this.mnemonicsByString.put("if_icmpne", 160);
        this.mnemonicsByString.put("if_icmplt", 161);
        this.mnemonicsByString.put("if_icmpge", 162);
        this.mnemonicsByString.put("if_icmpgt", 163);
        this.mnemonicsByString.put("if_icmple", 164);
        this.mnemonicsByString.put("if_acmpeq", 165);
        this.mnemonicsByString.put("if_acmpne", 166);
        this.mnemonicsByString.put("goto", 167);
        this.mnemonicsByString.put("jsr", 168);
        this.mnemonicsByString.put("ret", 169);
        this.mnemonicsByString.put("tableswitch", 170);
        this.mnemonicsByString.put("lookupswitch", 171);
        this.mnemonicsByString.put("ireturn", 172);
        this.mnemonicsByString.put("lreturn", 173);
        this.mnemonicsByString.put("freturn", 174);
        this.mnemonicsByString.put("dreturn", 175);
        this.mnemonicsByString.put("areturn", 176);
        this.mnemonicsByString.put("return", 177);
        this.mnemonicsByString.put("getstatic", 178);
        this.mnemonicsByString.put("putstatic", 179);
        this.mnemonicsByString.put("getfield", 180);
        this.mnemonicsByString.put("putfield", 181);
        this.mnemonicsByString.put("invokevirtual", 182);
        this.mnemonicsByString.put("invokespecial", 183);
        this.mnemonicsByString.put("invokestatic", 184);
        this.mnemonicsByString.put("invokeinterface", 185);
        this.mnemonicsByString.put("invokedynamic", 186);
        this.mnemonicsByString.put("new", 187);
        this.mnemonicsByString.put("newarray", 188);
        this.mnemonicsByString.put("anewarray", 189);
        this.mnemonicsByString.put("arraylength", 190);
        this.mnemonicsByString.put("athrow", 191);
        this.mnemonicsByString.put("checkcast", 192);
        this.mnemonicsByString.put("instanceof", 193);
        this.mnemonicsByString.put("monitorenter", 194);
        this.mnemonicsByString.put("monitorexit", 195);
        this.mnemonicsByString.put("wide", 196);
        this.mnemonicsByString.put("multianewarray", 197);
        this.mnemonicsByString.put("ifnull", 198);
        this.mnemonicsByString.put("ifnonnull", 199);
        this.mnemonicsByString.put("goto_w", 200);
        this.mnemonicsByString.put("jsr_w", 201);

        this.mnemonicsByString.forEach((mnemonic, opcode) -> this.mnemonicsByOpcode.put(opcode, mnemonic));
    }

    public String getMnemonicByOpcode(Integer mnemonic) {
        return this.mnemonicsByOpcode.get(mnemonic);
    }

    public Integer getOpcodeByMnemonic(String mnemonic) {
        return this.mnemonicsByString.get(mnemonic);
    }

}
